rules:
  master:
    level: off
  masterdata:
    level: warning
    regex:
      - /\b(?!masterdata\b)master/gi
    alternatives:
      - primary
      - main
      - leader
      - active
      - writer
    
